export const grid = [
  [
    {
      row: 0,
      col: 0,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 0,
      col: 1,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 0,
      col: 2,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 0,
      col: 3,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
  ],
  [
    {
      row: 1,
      col: 0,
      fScore: Infinity,
      Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 1,
      col: 1,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 1,
      col: 2,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 1,
      col: 3,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
  ],
  [
    {
      row: 2,
      col: 0,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 2,
      col: 1,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 2,
      col: 2,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 2,
      col: 3,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
  ],
  [
    {
      row: 3,
      col: 0,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 3,
      col: 1,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 3,
      col: 2,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
    {
      row: 3,
      col: 3,
      fScore: Infinity,
      gScore: Infinity,
      hScore: Infinity,
    },
  ],
];
